---
name: 'Dokku Push'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: easy-node-pro/github-action@master
        if: github.ref == 'refs/heads/main'
        with:
          branch: 'master'
          git_remote_url: 'ssh://dokku@easynode.pro:22/store.portfolio.pmtservicesincwi.com'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
